config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'contracts#home'
  get 'contracts/index', to: 'contracts#index'
  
  resources :lines do
    member do
      put :set_status_inactive
    end
    member do
      get 'duplicate'
    end
  end
  
  resources :cfiles
  
  resources :contracts do
    member do
      put :set_status_inactive
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line.rb
class Line < ApplicationRecord
    validates :contract_id, presence: true
    validates :prod_category_id, presence: true
    validates :city_id, presence: true
    validates :volume, presence: true
    validates :volume, :numericality => { :greater_than10 => 100 }
    validates :volume_grossnet, presence: true
    validates :formula, presence: true
    validate :sum_equals_100
    validate :index_present
    belongs_to :contract
    has_one :prod_category
    has_one :product
  
    def sum_equals_100
        if !index_1.blank?
            if pct_index_1.to_i + pct_index_2.to_i + pct_index_3.to_i != 100
              errors.add(:base, 'Index percentages must sum up to 100')
            end
        end
    end
    
    def index_present
        if formula == "Rack Posted"
            if rack_discount.blank?
              errors.add(:base, 'Rack discount cannot be blank')
            end
        elsif formula == "OPIS"
            if opis_grossnet.blank?
              errors.add(:base, 'OPIS Gross/Net cannot be blank')
            end
            if opis_index_point.blank?
              errors.add(:base, 'OPIS Index Point cannot be blank')
            end
            if opis_avglow.blank?
              errors.add(:base, 'OPIS Low cannot be blank')
            end
        else
            if index_1.blank?
              errors.add(:base, 'Index(es) cannot be blank')
            end
            if formula_samepriorday.blank?
              errors.add(:base, 'Index same/prior day cannot be blank')
            end
        end
    end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  # def index
  #   @lines = Line.where("status <> 'I'").order(updated_at: :desc)
  # end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
    @contract = Contract.find(params[:contract])
  end

  # GET /lines/1/edit
  def edit
    @contract = Contract.find(@line.contract_id)
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)
    @contract = Contract.find(@line.contract_id)
      if @line.save
        redirect_to @line, success: 'Line was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    @contract = Contract.find(@line.contract_id)
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, warning: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def set_status_inactive
      @line = Line.find params[:id]
      @contract = Contract.find(@line.contract_id)
      @line.update(:status => "I")
      redirect_to @contract, danger: 'Contract line was successfully deleted.'
  end
  
  def duplicate
      @line = Line.find(params[:id]) # find original object
      @line = Line.new(@line.attributes.except('id','created_at','updated_at','created_by','updated_by')) # initialize duplicate (not saved)
      @contract = Contract.find(@line.contract_id)
      render :new, notice: 'Line was successfully duplicated. Click Create Line to save.'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:formula, :volume, :contract_id, :product_id, :prod_category_id,
                                    :city_id, :terminal_id, :cancel_date, :status, :payment_terms,
                                    :volume_variance, :volume_grossnet, :formula_description, 
                                    :formula_samepriorday, :pct_ethanol, :index_1, :adder_1, :pct_index_1,
                                    :index_2, :adder_2, :pct_index_2, :index_3, :adder_3, :pct_index_3,
                                    :adder_inout, :adder_schedule, :pct_rins_discount, :index_rins,
                                    :summer_rvp, :rack_discount, :rack_discount_policy, :rebate_policy,
                                    :penalty_policy, :short_list, :created_by, :updated_by, :opis_grossnet, :opis_index_point, :opis_avglow)
    end
    
end

app/helpers/lines_helper.rb
module LinesHelper
    IndexOption = [
        ["Argus",[
        "Argus Diesel ULSD Chicago pipe fob cycle 1 - Houston close",
        "Argus Diesel ULSD Chicago pipe fob cycle 2 - Houston close",
        "Argus Diesel ULSD Colonial 62 pipe fob cycle 1 - Houston close",
        "Argus Diesel ULSD Group 3 Magellan X pipe fob prompt Prmpt - Houston close",
        "Argus Diesel ULSD NYH barge fob prompt Prmpt - Houston close",
        "Argus Distillates line space Colonial Line02 cycle 1 - Houston close",
        "Argus Ethanol Chicago Argo in-tank transfer month 1 - Houston close",
        "Argus Fuel oil bunker 380 cst Los Angeles Prmpt - Houston close",
        "Argus Gasoline 87 conv Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline 87 conv Colonial M pipe fob lowest RVP wtd avg cycle 1 - Houston close",
        "Argus Gasoline 89 conv Chicago pipe fob cycle Prmpt - Houston close",
        "Argus Gasoline 91 conv Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline 91 conv Group 3 Magellan A pipe fob Prmpt - Houston close",
        "Argus Gasoline 93 conv Colonial V pipe fob lowest RVP cycle 1 - Houston close",
        "Argus Gasoline 93 conv USGC waterborne fob lowest RVP Prmpt - Houston close",
        "Argus Gasoline line space Colonial Line01 cycle 1 - Houston close",
        "Argus Gasoline prem CBOB Colonial D pipe fob lowest RVP cycle 1 - Houston close",
        "Argus Gasoline prem CBOB NYH barge fob prompt continuous Prmpt - Houston close",
        "Argus Gasoline prem RBOB Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline prem RBOB Colonial H pipe fob cycle 1 - Houston close",
        "Argus Gasoline prem RBOB NYH barge fob prompt continuous Prmpt - Houston close",
        "Argus Gasoline reg CBOB Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline reg CBOB Colonial A pipe fob lowest RVP cycle 1 - Houston close",
        "Argus Gasoline reg CBOB NYH barge fob lowest RVP not 7.8 or 7.0 prompt Prmpt - Houston close",
        "Argus Gasoline reg RBOB Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline reg RBOB Colonial F pipe fob cycle 1 - Houston close",
        "Argus Gasoline reg RBOB Colonial F pipe fob cycle 2 - Houston close",
        "Argus Gasoline reg RBOB NYH barge fob prompt continuous Prmpt - Houston close",
        "Argus Heating oil NYH barge fob prompt Prmpt - Houston close"]],
        ["NYMEX",[
        "NYM ULSD NY HARBOR #2 (PIT) - Month (2nd Month)",
        "NYM ULSD NY HARBOR #2 (PIT) - Month (Front Month)",
        "NYMEX Light Sweet Crude Oil (WTI) Futures Electronic (Front Month)",
        "NYMEX Light Sweet Crude Oil (WTI) Futures Pit (Front Month)",
        "NYMEX NY Harbor ULSD Futures Pit",
        "NYMEX NY Harbor ULSD Futures Pit (2nd Month)",
        "NYMEX RBOB Gasoline Financial Futures Electronic (Front Month)",
        "NYMEX RBOB Gasoline Futures Electronic (Front Month)",
        "NYMEX RBOB Gasoline Futures Pit (2nd Month)",
        "NYMEX RBOB Gasoline Futures Pit (Front Month)"]],
        ["Platts",[
        "Platts DTN ULSD Regina SK RkAvg",
        "Platts DTN ULSD Regina SK UnbAvg",
        "Platts Ethanol Chicago Pipe",
        "Platts Ethanol FOB Houston Barge",
        "Platts Ethanol NYH Barge Mo01",
        # "Platts Ethanol RIN Cal Yr02",
        "Platts Gasoil No.2 New York Harbor Barge",
        "Platts Gasoil No.2 USGC Prompt Pipeline",
        "Platts Gasoline CARBOB San Francisco CA Pipeline",
        "Platts Gasoline CBOB 87 USGC Houston Prompt Pipeline",
        "Platts Gasoline CBOB 87 USGC Waterborne",
        "Platts Gasoline CBOB 93 USGC Houston Prompt Pipeline",
        "Platts Gasoline CBOB Chicago Pipe",
        "Platts Gasoline CBOB NY Barge",
        "Platts Gasoline PBOB Chicago Pipe",
        "Platts Gasoline Prem RBOB NY Barge",
        "Platts Gasoline Prem Unl 91 Group 3 Pipeline",
        "Platts Gasoline Prem Unleaded 91 Chicago Pipe",
        "Platts Gasoline RBOB 83.7 USGC Houston prompt pipeline",
        "Platts Gasoline RBOB 91.4 USGC Houston Prompt Pipeline",
        "Platts Gasoline RBOB Chicago Pipe",
        "Platts Gasoline RBOB NY Barge",
        "Platts Gasoline RBOB NY Cargo",
        "Platts Gasoline Reg Unl San Francisco CA Pipeline",
        "Platts Gasoline Unl 87 NY Barge",
        "Platts Gasoline Unl 87 USGC Prompt Pipeline",
        "Platts Gasoline Unl 93 NY Barge",
        "Platts Gasoline Unl 93 USGC Prompt Pipeline",
        "Platts Gasoline Unl Sub Octane Group 3 Pipeline",
        "Platts Gasoline Unleaded 87 Chicago Pipe",
        "Platts Gasoline Unleaded 89 Chicago Pipe",
        "Platts Jet Kero 54 USGC Prompt Pipeline",
        "Platts Jet Kero Group 3 Pipeline",
        "Platts Jet Kero ULS No1 FOB Chicago Pipe",
        "Platts NYMEX NY ULSD 01-Mo Floor",
        "Platts NYMEX NY ULSD at Houston MOC Mo01",
        "Platts NYMEX NY ULSD at Houston MOC Mo02",
        "Platts NYMEX RBOB 01-Mo Floor",
        "Platts NYMEX RBOB at Houston MOC Mo01",
        "Platts NYMEX RBOB at Houston MOC Mo02",
        "Platts ULS Heating Oil USGC Prompt Pipeline",
        "Platts ULSD (EPA) Portland OR Pipeline",
        "Platts ULSD FOB Chicago Pipe",
        "Platts ULSD Group 3 Pipeline",
        "Platts ULSD New York Harbor Barge",
        "Platts ULSD No2 CARB Diesel San Francisco CA Pipeline",
        "Platts ULSD USGC Prompt Pipeline",
        "Platts ULSD USGC Waterborne"]]
        ]
end

app/views/lines/_formline.html.erb
<%= form_for(line) do |f| %>
  <% if line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	</p>


<div class="form-group row">
  <div class="field">
    <label for="inputContractId" class="col-2 col-form-label"><%= f.label :contract_id, "Contract ID" %></label>
    <%= f.number_field :contract_id, class: "form-control", :value => line.contract_id, :readonly => true %>
  </div>
</div>

<div class="form-group row">
    <div class="field">
      <label class="col-2 col-form-label"><%= f.label :prod_category_id, "Product Category* (DTN)" %></label>
      <% options = options_from_collection_for_select(ProdCategory.order(:name), 'id', 'name', f.object.prod_category_id ) %>
      <%= f.select(:prod_category_id, options, {include_blank: !line.prod_category_id.present? }, { :class => "form-control", :id =>"prod-category" }) %>
    </div>
</div>

<div class="form-group row">
    <div class="field">
      <label class="col-2 col-form-label"><%= f.label :product_id, "Product (DTN)" %></label>
      <% options = option_groups_from_collection_for_select(ProdCategory.order(:name), :products, :name, :id, :name,  f.object.product_id ) %>
      <%= f.select(:product_id, options, {include_blank: !line.product_id.present? }, { :class => "form-control", :id =>"prod-name" } ) %>
    </div>
</div>

<div class="form-group row">
  <div class="field">
    <label for="inputFormula" class="col-2 col-form-label"><%= f.label :formula %></label>
    <%= f.text_field :formula, class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <div class="field">
    <label for="inputVolume" class="col-2 col-form-label"><%= f.label :volume %></label>
    <%= f.number_field :volume, class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
</div>

<% end %>

app/views/lines/_line.html.erb
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th class="muted">Line ID</th>
      <th>Product Group</th>
      <th>Product</th>
      <th>City</th>
      <th>Terminal</th>
      <th>Formula</th>
      <th style="text-align:right">Canceled?</th>
      <th style="text-align:right">Volume</th>
      <th style="text-align:right">Last Updated</th>      
      <th colspan="10"></th>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |line| %>
      <tr>
        <td class="muted"><%= line.id %></td>
        <td><%= ProdCategory.find(line.prod_category_id).name %></td>
        <td><%= Product.searchfield(line.product_id,'abbr') %></td>
        <td><%= City.find(line.city_id).name %></td>
        <td><%= Terminal.searchfield(line.terminal_id,'abbr') %></td>
        <td><%= line.formula %></td>
        <td align="right"><% if line.cancel_date.present? %>
                        <%= yesno(line.cancel_date < Date.today) %>
                        <% end %>
        </td>
        <td align="right"><%= number_with_delimiter(line.volume, delimiter: ",")  %></td>
        <td align="right"><%= line.updated_at.strftime("%m/%d/%Y") %></td>
        <td align="right"><%#= line.status %></td>
        <td>
          <div class="dropdown pull-right">
            <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> &nbsp;
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to 'Details', line %></li>
              <li><%= link_to 'Edit', edit_line_path(line) %></li>
              <li>
                <%= link_to 'Duplicate', duplicate_line_path(line), method: :get %>
              </li>
              <li>
                <%= link_to 'Delete', set_status_inactive_line_path(line), method: :put, data: { confirm: 'Are you sure?' } %>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lines/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
    <h1 class="inline-block"><img class="document-icon" src="/document.png" />
    Editing Line</h1>
    <div class="mandatory-text">Fields with * are mandatory.</div>
  </div>
  <div class="bottom-align-right col-xs-6 col-md-4">
    <ul class="nav nav-pills pull-right">
    	<li><%= button_to 'Details', line_path(@line), method: :get, class:"btn btn-default" %></li>
			<li><%= button_to 'Back', contract_path(@line.contract_id), method: :get, class:"btn btn-default" %></li>
		</ul>
  </div>
</div>

<%= render 'lineform', line: @line %>

  <div class="min-height"></div>

app/views/lines/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
    <h1 class="inline-block"><img class="document-icon" src="/document.png" />
      New Contract Line</h1>
    <div class="mandatory-text">Fields with * are mandatory.</div>
  </div>
  <div class="bottom-align-right col-xs-6 col-md-4">
    <ul class="nav nav-pills pull-right">
	    <li><%= button_to 'Back', contract_path(@line.contract_id.presence || @contract.id), method: :get, class:"btn btn-default" %></li>
		</ul>
  </div>
</div>

<br>

<%= render 'lineform', line: @line %>

  <div class="min-height"></div>

app/views/lines/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
  	<h1><img class="document-icon" src="/document.png" />
  	Contract Line Details</h1>
  </div>
  <div class="bottom-align-right col-xs-6 col-md-4">
    <ul class="nav nav-pills pull-right">
    	<li><%= button_to 'Edit', edit_line_path(@line), method: :get, class:"btn btn-default" %></li>
    	<li><%= button_to 'Done', contract_path(@line.contract_id), method: :get, class:"btn btn-default" %></li>
		</ul>
  </div>
</div>
</br>

	<table class="table borderless">
		<tr>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Product Category</label>
					<input type="text" value="<%= ProdCategory.find(@line.prod_category_id).name %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Terminal City (DTN)</label>
					<input type="text" value="<%= City.find(@line.city_id).name  %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Volume Gross/Net</label>
					<input type="text" value="<%= @line.volume_grossnet  %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
		<tr>
			<td>
        <div class="field">
          <label class="col-2 col-form-label ">Product (DTN) </label>
					<input type="text" value="<%= Product.searchfield(@line.product_id,'name') + "  (" + Product.searchfield(@line.product_id,'abbr') + ")" if Product.find_by_id(@line.product_id).present? %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Terminal Operator (DTN)</label>
					<input type="text" value="<%= Terminal.searchfield(@line.terminal_id,'abbr') + "  (" + Terminal.searchfield(@line.terminal_id,'tcn') + ")" if Terminal.find_by_id(@line.terminal_id).present? %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Volume (Gallons)</label>
          <input type="text" value="<%= number_with_delimiter(@line.volume,delimiter: ",") %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
		<tr>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Cancel Date (if canceled)</label>
           <input type="date" value="<%= @line.cancel_date %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Payment Terms</label>
          <input type="text" value="<%= @line.payment_terms %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Volume Variance Allowed</label>
          <input type="text" value="<%= @line.volume_variance %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
		<tr>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Formula</label>
					<input type="text" value="<%= @line.formula  %>" class="form-control" readonly=true id="formula-source" >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Formula Same/Prior Day</label>
					<input type="text" value="<%= @line.formula_samepriorday  %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Formula Description</label>
          <input type="text" value="<%= @line.formula_description %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
		<tr class="opis-fields">
			<td>
        <div class="field">
          <label class="col-2 col-form-label">OPIS Gross/Net</label>
					<input type="text" value="<%= @line.opis_grossnet  %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">OPIS Index Point</label>
					<input type="text" value="<%= @line.opis_index_point %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">OPIS Low</label>
          <input type="text" value="<%= @line.opis_avglow%>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
		<tr class="index-fields">
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Index 1</label>
          <input type="text" value="<%= @line.index_1 %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Index 2</label>
          <input type="text" value="<%= @line.index_2 %>" class="form-control" readonly=true >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Index 3</label>
          <input type="text" value="<%= @line.index_3 %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
    <tr class="index-fields">
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Product 1 Mix%</label>
          <input type="number" value="<%= @line.pct_index_1 %>" class="form-control" readonly=true >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Product 2 Mix%</label>
          <input type="number" value="<%= @line.pct_index_2 %>" class="form-control" readonly=true >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Product 3 Mix%</label>
          <input type="number" value="<%= @line.pct_index_3 %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
		<tr class="index-fields">
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Adder 1</label>
          <input type="number" value="<%= @line.adder_1 %>" class="form-control" readonly=true, step:"any" >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Adder 2</label>
          <input type="number" value="<%= @line.adder_2 %>" class="form-control" readonly=true, step:"any" >
        </div>
      </td>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Adder 3</label>
          <input type="number" value="<%= @line.adder_3 %>" class="form-control" readonly=true, step:"any" >
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Adder Blend/Component</label>
          <input type="text" value="<%= @line.adder_inout %>" class="form-control" readonly=true >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Adder/TVA Schedule</label>
          <input type="text" value="<%= @line.adder_schedule %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
    <tr class="index-fields">
      <td>
        <div class="field">
          <label class="col-2 col-form-label">RINS Index</label>
          <input type="text" value="<%= @line.index_rins %>" class="form-control" readonly=true >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">RINS Discount %</label>
          <input type="number" value="<%= @line.pct_rins_discount %>" class="form-control" readonly=true >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Ethanol %</label>
          <input type="number" value="<%= @line.pct_ethanol %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
    <tr class="rackposted-fields">
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Rack Posted Price Discount</label>
          <input type="number" value="<%= @line.rack_discount %>" class="form-control" readonly=true, step:"any" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Rack Discount Policy</label>
          <input type="text" value="<%= @line.rack_discount_policy %>" class="form-control" readonly=true >
        </div>
      </td>
      <td>
        <div class="field hide">
          <label class="col-2 col-form-label">Line Status</label>
          <input type="text" value="<%= @line.status %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Rebate Policy</label>
          <textarea type="text" class="form-control" readonly=true ><%= @line.rebate_policy %></textarea>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Penalty Policy</label>
          <textarea type="text" class="form-control" readonly=true ><%= @line.penalty_policy %></textarea>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Has Summer RVP Grade</label>
          <input type="text" value="<%= @line.summer_rvp %>" class="form-control" readonly=true >
        </div>
      </td>
    </tr>
  </table>
  
  <div class="min-height"></div>