config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'contracts#home'
  get 'contracts/index', to: 'contracts#index'
  
  resources :lines do
    member do
      put :set_status_inactive
    end
    member do
      get 'duplicate'
    end
  end
  
  resources :cfiles
  
  resources :contracts do
    member do
      put :set_status_inactive
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contract.rb
class Contract < ApplicationRecord
    # validates :contract_nbr, presence: true
    validates :supplier, presence: true
    validates :sales_rep, presence: true
    validates :market_id, presence: true
    validates :brand_type, presence: true, allow_blank: false
    validates :start_date, presence: true
    # validates :end_date, presence: true
    validates :renew_type, presence: true
    validates :formula_type, presence: true
    validates :pricing_cycle, presence: true
    validate :end_after_start
    validate :end_if_not_evergreen
    has_many :lines
    has_one :cfile
    has_one :market
    
    def end_after_start
        if !end_date.nil?
            if end_date <= start_date
               errors.add(:base, 'End date must be after Start date')
            end
        end
    end
    
    def end_if_not_evergreen
        if renew_type != "Evergreen"
            if end_date.nil?
               errors.add(:base, 'End date cannot be blank if renewal cycle is not evergreen')
            end
        end
    end
    
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :set_status_inactive]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.where("status <> 'I'").order(updated_at: :desc)
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
    if @contract.cfile
      @cfile = @contract.cfile
    else
      @cfile = Cfile.new
    end
    # @lines = Line.where("status <> 'I'").order(updated_at: :desc)
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, success: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, warning: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  # PUT /contracts/1
  def set_status_inactive
      @contract = Contract.find params[:id]
      @contract.update(:status => "I")
      redirect_to contracts_url, danger: 'Contract was successfully deleted.'
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, danger: 'Contract was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:contract_nbr, :sales_rep, :supplier, :supplier_nbr, 
                    :status, :company, :market_id, :start_date, :end_date, :renew_type,
                    :formula_type, :pricing_cycle, :brand_type, :notes, :created_by, :updated_by)
    end
    
end

app/helpers/contracts_helper.rb
module ContractsHelper
  SalesrepOption = [
  "Achten, David J",
  "Allen, Mr. Harry",
  "Anderson, Chris",
  "Anselm, Michael Scott",
  "Baas, Christopher T",
  "Baldwin Jr, Robert R",
  "Barnes, Dean",
  "Bishop, Joe",
  "Bonneau, Mr. Robert",
  "Brongel, Edward",
  "Cappello, Daniel",
  "Clifton, Josh",
  "Coleman, Mary Susan",
  "Colley, Terry L",
  "Cooper, Tim",
  "Cox, Michael",
  "Dabbas, Sami",
  "Dean, Mr. Devesha",
  "Denk, Mr. Nathan",
  "Dharani, Zulfiquarali M",
  "Dill, Jason B",
  "Dobry, Robert J",
  "Edwards, Tara A",
  "Farmer, William M",
  "Gagliardo, Catherine",
  "Hackerott, Aaron S",
  "Hartnett, George",
  "Hoffman, Mr. Mark",
  "Horning, David Todd",
  "House Alta Fuels",
  "House Carter",
  "House Lakeside",
  "House Texor",
  "Huber, Gerald A",
  "Hudson-Miltenberger, Jason M",
  "Hurley, Annette",
  "James, Aaron T",
  "Janson, Michelle",
  "Kaegebein, Erin E",
  "Kalis, Brian D",
  "Kilpatrick, Ms. Beth A",
  "Kisch, Mr. Kevin",
  "Kittrell, Michael W",
  "Kraft, Paul",
  "Latcham, Ronnie L",
  "Lee, Robert E",
  "Livermore, Lewis C",
  "Ludwig, Mr. Michael",
  "Ludwig, Paul",
  "Luehmann, Mark",
  "Lundquist, Michael",
  "Maes, Lucas",
  "Mannion, John",
  "Marable, Mrs. Shelly",
  "McCoy, Loresa K",
  "McGill, Eric D",
  "McKelvey, Mr. William P.",
  "McLemore, Ms. Traci",
  "McLeod, Garth",
  "McNally, Mr. Robert J",
  "Mercil, Miss Colleen",
  "Milligan, David J",
  "Milligan, Michael J",
  "Milligan, Tyler Jon",
  "Monty, Mr. Chad M",
  "Mortensen, Chad R",
  "Mullins, Joel",
  "Nelson, Kurt E",
  "Nigro, Austin J",
  "Oesterreich, Mr. Paul E",
  "Ohara, Mr. Dennis",
  "Penrod, Robert M",
  "Pittala, Lenny",
  "Powers, Mark",
  "Prosser, James S",
  "Rand, Scott",
  "Reilly, Mr. Stuart P",
  "Rodrigues, Michael A",
  "Rogers, Steven",
  "Sammons, James L",
  "Schroeder, Binny",
  "Shepherd, Tyler",
  "Shireman, Mr. William H",
  "Singh, Akash",
  "Smith, Aaron",
  "Sobczak, Mr. John",
  "Speropulos, George",
  "St Martin, Mr. Jason",
  "Steoger, Mr. Samuel D. (Sam)",
  "Stergiou, Stefanos",
  "Tappan, Jayme L",
  "Thomas, James V",
  "Thomas, Raymond E",
  "Whelan, Mr. Casey D"
  ]
  
end

app/views/contracts/_form.html.erb
<%= form_for(contract) do |f| %>

<div class="container">
  <div class="row">
  <% if contract.errors.any? %>
    <div id="error_explanation" class="alert alert-danger fade in">
      <h2>Oh snap! Change a few things up and try submitting again.</h2>
      <ul>
      <% contract.errors.full_messages.each do |message| %>
        <li><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>&nbsp;&nbsp;<%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>
</div>

<br>

  <div class="field hide">
    <%= f.number_field :created_by, class: "form-control", :value => contract.created_by.presence || current_user.id %>
    <%= f.number_field :updated_by, class: "form-control", :value => current_user.id %>
  </div>

	<table class="table borderless">
		<tr>
			<td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :contract_nbr, "Contract Number" %></label>
          <%= f.number_field :contract_nbr, class: "form-control" %>
        </div>
      </td>
			<td>
          <div class="field">
            <label class="col-2 col-form-label"><%= f.label :supplier, "Supplier* (DTN)" %></label>
            <% options = options_from_collection_for_select(Supplier.order(:name), 'name', 'name', f.object.supplier ) %>
            <%= f.select(:supplier, options, {include_blank: !@contract.supplier.present? }, { :class => "form-control" }) %>
          </div>
      </td>
			<td>
          <div class="field">
            <label class="col-2 col-form-label"><%= f.label :supplier_nbr, "Supplier Number (Oracle)" %></label>
            <%= f.text_field :supplier_nbr, class: "form-control" %>
          </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :company %></label>
          <%= f.select(:company, ["","Legacy","CarterEnergy", "Lakeside","Texor","Western","Alta","APP","PAPCO"], {}, { :class => "form-control" }) %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Market State</label>
              <% if f.object.market_id.present? %>
              <%   selected = Market.find(f.object.market_id).state.name %>
              <% end %>
            <% options = options_from_collection_for_select(State.where("country = 'USA'").order(:name), 'name', 'name', selected ) %>
            <%= select_tag('', options, include_blank: @contract.market_id.blank? , class:"form-control", id:"market-state") %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :market_id, "Market* (DTN)" %></label>
            <% options = option_groups_from_collection_for_select(State.where("country = 'USA'").order(:name), :markets, :name, :id, :name,  f.object.market_id ) %>
            <%= f.select(:market_id, options, {include_blank: @contract.market_id.blank? }, { :class => "form-control", :id =>"market-name" }) %>
        </div>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :brand_type, "Brand Type*"  %></label>
          <%= f.select(:brand_type, ["", "U", "B"], {}, { :class => "form-control" }) %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :start_date, "Start Date*" %></label>
          <%= f.date_field :start_date, class: "form-control" %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :end_date, "End Date" %></label>
          <%= f.date_field :end_date, class: "form-control" %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :renew_type, "Renewal Cycle*" %></label>
          <%= f.select(:renew_type, ["","Yearly","Monthly", "Evergreen","Other"], {}, { :class => "form-control" }) %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :formula_type, "Formula Type*" %></label>
          <%= f.select(:formula_type, ["","Index","Rack Posted", "Either/Or","Monthly Average","Other"], {}, { :class => "form-control" }) %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :pricing_cycle, "Pricing Cycle*" %></label>
          <%= f.select(:pricing_cycle, ["","12am-12am","6pm-6pm","5pm-5pm","7pm-7pm","Other"], {}, { :class => "form-control dropbdown-hide" }) %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :notes %></label>
          <%= f.text_area :notes, class: "form-control" %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :sales_rep,"Sales Rep*" %></label>
          <%= f.select :sales_rep, options_for_select(ContractsHelper::SalesrepOption,f.object.sales_rep), {include_blank: !contract.sales_rep.present?}, { :class => "form-control"}  %>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label"><%= f.label :status %></label>
          <input type="text" class="form-control" id="inputStatus" value="A" readonly=true >
          <%= f.hidden_field :status, :value => 'A' %>
        </div>
      </td>
    </tr>
  </table>
  
<div class="form-group row min-height">
  <div class="actions">
    <%= f.submit class:"btn btn-primary pull-down" %>
  </div>
</div>
  
<% end %>

app/views/contracts/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
    <h1 class="inline-block"><img class="document-icon" src="/document.png" />
    Edit Contract</h1>
    <div class="mandatory-text">Fields with * are mandatory.</div>
  </div>
  <div class="bottom-align-right col-xs-6 col-md-4">
    <ul class="nav nav-pills pull-right">
    	<li><%= button_to 'Details', contract_path(@contract), method: :get, class:"btn btn-default" %></li>
	    <li><%= button_to 'Back', contracts_path, method: :get, class:"btn btn-default" %></li>
		</ul>
  </div>
</div>

<%= render 'form', contract: @contract %>

app/views/contracts/home.html.erb
<div class="row">
  <div class="center-outer">
    <div class="home-button1">
      <a href="/contracts"> 
        <div class="hyperspan"></div>
      </a>
      <div class="home-button-text text-center">S</div>
      <div class="home-button-text-sm text-center">
        Supplier Contract Database
      </div>
    </div>
    <div class="home-button2">
      <a href="/contracts"> 
        <div class="hyperspan"></div>
      </a>
      <div class="home-button-text text-center">C</div>
      <div class="home-button-text-sm text-center">
        Customer Contract Database
      </div>
    </div>
  </div>
</div>

app/views/contracts/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
    <h1><img class="document-icon" src="/document.png" />
    Supply Contracts</h1>
  </div>
  <div class="bottom-align-right col-xs-6 col-md-4">
    <%= button_to 'Create New', new_contract_path, method: :get, class:"btn btn-primary pull-right" %>
  </div>
</div>

<br>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th class="muted">ID</th>
      <th>Contract #</th>
      <th>Supplier</th>
      <th>Market</th>
      <th>Brand</th>
      <th>Start Date</th>
      <th>Formula Type</th>
      <th>Lines</th>
      <th>Last Updated</th>
      <th>&nbsp;</th>
      <th colspan="9"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td class="muted"><%= contract.id %></td>
        <td><%= contract.contract_nbr %></td>
        <td><%= contract.supplier %></td>
        <td><%= Market.find(contract.market_id).market %></td>
        <td><%= contract.brand_type %></td>
        <td><%= contract.start_date.strftime("%m/%d/%Y") %></td>
        <td><%= contract.formula_type %></td>
        <td align="right"><%= contract.lines.where("status='A'").count %></</td>
        <!--<td align="right"><%#= number_with_delimiter(contract.lines.sum(:volume), delimiter: ",") if contract.lines %></</td>-->
        <td align="center"><%= contract.updated_at.strftime("%m/%d/%Y") %></td>
        <td align="right">
          <a id="attachment-link" target="_blank" href=<% if contract.cfile.present? %>
                  <%= contract.cfile.document %>
                  <% else %>
                  <%= "\"\" hidden" %>
                  <% end %> >
          <img src="/attachment.png" title="has attachment"/>
          </a>
        </td>
        <td>
          <div class="dropdown pull-right">
            <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> &nbsp;
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to 'Details', contract %></li>
              <li><%= link_to 'Edit', edit_contract_path(contract) %></li>
              <li>
                <%= link_to 'Delete', set_status_inactive_contract_path(contract), method: :put, data: { confirm: 'Are you sure that you want to delete?' } %>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contracts/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
    <h1 class="inline-block"><img class="document-icon" src="/document.png" />
      New Contract</h1>
    <div class="mandatory-text">Fields with * are mandatory.</div>
  </div>
  <div class="bottom-align-right col-xs-6 col-md-4">
    <ul class="nav nav-pills pull-right">
	    <li><%= button_to 'Back', contracts_path, method: :get, class:"btn btn-default" %></li>
		</ul>
  </div>
</div>

<br>

<%= render 'form', contract: @contract %>

app/views/contracts/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
  	<h1><img class="document-icon" src="/document.png" />
  	Contract Header Details</h1>
  </div>
  <div class="bottom-align-right col-xs-6 col-md-4">
    <ul class="nav nav-pills pull-right">
    	<li><%= button_to 'Edit', edit_contract_path(@contract), method: :get, class:"btn btn-default" %></li>
    	<li><%= button_to 'Done', contracts_path, method: :get, class:"btn btn-default" %></li>
		</ul>
  </div>
</div>
</br>

	<table class="table borderless">
		<tr>
			<td>
        <div class="field">
          <label class="col-2 col-form-label">Contract Number</label>
          <input type="number" class="form-control" readonly=true value="<%= @contract.contract_nbr%>" >
        </div>
      </td>
			<td>
          <div class="field">
            <label class="col-2 col-form-label">Supplier (DTN)</label>
            <input type="text" class="form-control" readonly=true value="<%= @contract.supplier%>" >
          </div>
      </td>
			<td>
          <div class="field">
            <label class="col-2 col-form-label">Supplier Number (Oracle)</label>
            <input type="text" class="form-control" readonly=true value="<%= @contract.supplier_nbr %>" >
          </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Company</label>
          <input type="text" class="form-control" readonly=true value="<%= @contract.company%>" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Market State</label>
          <input type="text" class="form-control" readonly=true value="<%= Market.find(@contract.market_id).state.name %>" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Market (DTN)</label>
          <input type="text" class="form-control" readonly=true value="<%= Market.find(@contract.market_id).name %>" >
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Brand Type</label>
          <input type="text" class="form-control" readonly=true value="<%= @contract.brand_type%>" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Start Date</label>
          <input type="date" class="form-control" readonly=true value="<%= @contract.start_date%>" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">End Date</label>
          <input type="date" class="form-control" readonly=true value="<%= @contract.end_date%>" >
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Renewal Cycle</label>
          <input type="text" class="form-control" readonly=true value="<%= @contract.renew_type%>" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Formula Type</label>
          <input type="text" class="form-control" readonly=true value="<%= @contract.formula_type%>" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Pricing Cycle</label>
          <input type="text" class="form-control" readonly=true value="<%= @contract.pricing_cycle%>" >
        </div>
      </td>
    </tr>
    <tr>
      <td rowspan="2">
        <div class="field">
          <label class="col-2 col-form-label">Notes</label>
          <textarea type="text" class="form-control textarea-rowspan2" readonly=true ><%= @contract.notes%></textarea>
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Sales Rep</label>
          <input type="text" class="form-control" readonly=true value="<%= @contract.sales_rep%>" >
        </div>
      </td>
      <td>
        <div class="field">
          <label class="col-2 col-form-label">Status</label>
         <input type="text" class="form-control" readonly=true value="<%= @contract.status%>" >
        </div>
      </td>
    </tr>
    <tr colspan="2">
      <td colspan="2">
      <%= render 'cfiles/cfile', cfile_obj: @cfile %>
      </td>
    </tr>
  </table>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
    <h2>Contract Lines</h2>
  </div>
  <div class="bottom-align-right-h2 col-xs-6 col-md-4">
    <%= link_to 'New Line', new_line_path(:contract => @contract.id), method: :get, class:"a btn btn-primary pull-right" %>
  </div>
</div>

<br>

  <div class="min-height">
	<%= render 'lines/line', obj: @contract.lines.where("status='A'").order(city_id: :asc,terminal_id: :asc,prod_category_id: :asc,product_id: :asc,updated_at: :asc) %>
	</div>
