config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'contracts#home'
  get 'contracts/index', to: 'contracts#index'
  
  resources :lines do
    member do
      put :set_status_inactive
    end
    member do
      get 'duplicate'
    end
  end
  
  resources :cfiles
  
  resources :contracts do
    member do
      put :set_status_inactive
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cfile.rb
class Cfile < ApplicationRecord
  belongs_to :contract, required: false , :class_name => "contract", :foreign_key => "contract_id"
  validates :document, presence: true
  validates :contract_id, presence: true
  mount_uploader :document, DocumentUploader
  
end

app/controllers/cfiles_controller.rb
class CfilesController < ApplicationController
  before_action :set_cfile, only: [:show, :edit, :update, :destroy]
  # protect_from_forgery except: :update

  # GET /cfiles
  # GET /cfiles.json
  def index
    @cfiles = Cfile.all
  end

  # GET /cfiles/1
  # GET /cfiles/1.json
  def show
  end

  # GET /cfiles/new
  def new
    @cfile = Cfile.new
  end

  # GET /cfiles/1/edit
  def edit
  end

  # POST /cfiles
  # POST /cfiles.json
  def create
    # @contract = Contract.find(cfile_params[:contract_id])
    @cfile = Cfile.new(cfile_params)
    
    puts cfile_params.inspect

    # respond_to do |format|
      # if 
        @cfile.save
        puts @cfile.errors.full_messages
        
        # format.html { render "contracts/show", notice: 'Cfile was successfully created.' }
        # format.json { render :show, status: :created, location: @cfile }
      # else
        # format.html { render "contracts/show" }
        # format.json { render json: @cfile.errors, status: :unprocessable_entity }
      # end
    # end
  end

  # PATCH/PUT /cfiles/1
  # PATCH/PUT /cfiles/1.json
  
  def update
    # @contract = Contract.find(cfile_params[:contract_id])

    puts cfile_params.inspect
    
    # respond_to do |format|
      # if 
        @cfile.update(cfile_params)
        puts @cfile.errors.full_messages
        
        # format.html { render "contracts/show", notice: 'Cfile was successfully updated.' }
        # format.json { render :show, status: :ok, location: @cfile }
      # else
        # format.html { render "contracts/show" }
        # format.json { render json: @cfile.errors, status: :unprocessable_entity }
      # end
    # end
  end

  # DELETE /cfiles/1
  # DELETE /cfiles/1.json
  def destroy
    @cfile.destroy
    respond_to do |format|
      format.html { redirect_to cfiles_url, notice: 'Cfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cfile
      @cfile = Cfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cfile_params
      #params.fetch(:cfile, {}).permit(:name, :document, :contract_id)
      params.require(:cfile).permit(:name, :document, :contract_id, :created_by, :updated_by)
    end
end

app/helpers/cfiles_helper.rb
module CfilesHelper
end

app/views/cfiles/_cfile.html.erb
<!--<%- model_class = Cfile -%>-->
<%= form_for cfile_obj, :html => { multipart: true, :class => "form-horizontal", remote:true , id: 'file-upload-form' } do |f| %>

    <%= f.hidden_field :created_by, :value => cfile_obj.created_by.presence || current_user.id %>
    <%= f.hidden_field :updated_by, :value => current_user.id %>

      <div class="half-width field inline-block valign-top">
        <label class="col-2 col-form-label" title="Accpets file types: .jpg/.png/.pdf">
          Attached Document
        </label>
        <input type="text"  title="Accpets file types: .jpg/.png/.pdf" class="form-control" id="document-name" readonly=true value="<%=File.basename( (cfile_obj.document.presence || 'Please upload a file =>').to_s) %>">
        <%= f.hidden_field :contract_id, :value => @contract.id %>
        <%#=f.error_span(:name) %>
      </div>
      <div class="half-width field inline-block">
        <label class="col-2 col-form-label">&nbsp;</label>
        <div class="inline-block">
            <div class="controls inline-block">
              <a class="btn btn-default btn-xs" id="download-btn" <%='disabled' if !cfile_obj.document.present? %> <%= "href=" + cfile_obj.document.to_s if cfile_obj.document.present? %> target="_blank">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                <span>&nbsp;Download</span>
              </a>
            </div>
            <div class="inline-block">
              <span class="btn btn-primary btn-xs btn-file" id="upload-btn-span">Upload New
                <%= f.file_field :document, accept:'image/jpeg,image/png,application/pdf', :id => 'upload-btn' %>
              </span>
              <%#= f.hidden_:document_cache, :value => cfile_obj.document_cache%>
              <%#= f.submit class:'btn btn-xs btn-default'%>
            </div>
            <div id="spinner" class="text-center spinner inline-block" style="display: none;" >
              <span class="glyphicon glyphicon-refresh spinning"></span>
            </div>
            <div class="inline-block text-success" id="file-upload-result" style="display: none;">
              Success!
            </div>
            <div class="inline-block text-danger" id="file-upload-error" style="display: none;">
              Error!
            </div>
        </div>
      </div>
<% end %>

app/views/cfiles/edit.html.erb
<%- model_class = Cfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'cfile', cfile_obj: @cfile %>

app/views/cfiles/index.html.erb
<%- model_class = Cfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:document) %></th>
      <th><%= model_class.human_attribute_name(:contract_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cfiles.each do |cfile| %>
      <tr>
        <td><%= link_to cfile.id, cfile_path(cfile) %></td>
        <td><%= cfile.name %></td>
        <td><%= cfile.document %></td>
        <td><%= cfile.contract_id %></td>
        <td><%=l cfile.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      cfile_path(cfile), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cfile_path(cfile), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cfile_path(cfile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cfile_path,
            :class => 'btn btn-primary' %>

app/views/cfiles/new.html.erb
<%- model_class = Cfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'cfile', cfile_obj: @cfile %>

app/views/cfiles/show.html.erb
<%- model_class = Cfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @cfile.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:document) %>:</strong></dt>
  <dd><%= @cfile.document %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contract_id) %>:</strong></dt>
  <dd><%= @cfile.contract_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              cfiles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cfile_path(@cfile), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cfile_path(@cfile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>