config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'contracts#home'
  get 'contracts/index', to: 'contracts#index'
  
  resources :lines do
    member do
      put :set_status_inactive
    end
    member do
      get 'duplicate'
    end
  end
  
  resources :cfiles
  
  resources :contracts do
    member do
      put :set_status_inactive
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom panel-footer">
  <div class="container">
    <small class="inline-block">
      Copyright &copy; 2017 World Fuel Services Corporation. All Rights Reserved.
    </small>
    <div class="pull-right">
      <a href="mailto:LandAnalytics@wfscorp.com?Subject=Supply%20Contract%20Database" target="_top" class="link-white">Contact Us</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("wfs_sm.png", border: 0), root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Supply Contracts", contracts_index_path %></li>
        <li><a href="#">Customer Contracts</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
              <li class="inline-block" id="current-user-alias">
                <a disabled class="inline-block"><%= current_user.email.split("@")[0].upcase %>:</a>
              </li>
              <li class="inline-block">
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
              </li>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WFS Land Contract Database" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%= render partial: "layouts/navigation" %>
	<%= render partial: "shared/flash_messages", flash: flash %>

	<div class="container">
    <%= yield %>
  </div>

  <%= render partial: "layouts/footer" %>
  
  <%#= debug(params) if Rails.env.development? %>

  </body>
</html>